### ISSUE TITLE
Name of candidate participant

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/gds-edemocracy#10]
**Is your feature request related to a problem? Please describe.**
When I request participants the response not include the name of candidate to delegate the vote.
I want the name to be displayed on the screen and the participating users know the name of the candidate to whom they delegate the vote

**Describe the solution you'd like**
Add name field to response of get participants

**Comment by vvalvesga** [comment]
[here](https://github.com/OpenReqEU/gds-edemocracy/pull/11) the pull request

**Comment by dfucci** [comment]
closed in 03331f8fa9a79821412f3e8ceca27544c4f6bef7
