### ISSUE TITLE
Lost votes

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/gds-edemocracy#12]
**Describe the bug**
In phase voting, candidates vote tickets. And when this phase finished, I can get a report with the results. But here I find an error because there are lost votes, the results are incorrect.
Example: When candidate1 vote ticket 100 and candidate2 vote and delete vote for ticket 100, both votes are deleted and the report return 0 votes for this ticket.

**To Reproduce**
 candidate1 vote ticket 100 
candidate2 vote ticket 100
candidate2 delete vote for ticket 100
both votes are deleted and the report return 0 votes for this ticket.

I use for vote: http://ip:9750/api/projects/98/participations/current/votes(PUT) and in the body:
{
  "votes": [
    100
  ]
}
And for delete, the array of body is empty

**Expected behavior**
No delete votes from other candidates

**Comment by dfucci** [comment]
Thank you for reporting this @vvalvesga, I will investigate this behavior.
The issue seems related to a lack of checks in the `update_votes/2` method https://github.com/OpenReqEU/gds-edemocracy/blob/f1a9272aa8caed943bc34c19fbd1cbaeac465fa9/lib/ex_vote/participations/participations.ex#L102-L130
