### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/gds-edemocracy#3]
**Describe the bug**
When I integrate this microservice in my application and I execute the call to create a project from the browser, an error returns

from origin 'http: // localhost: 4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**To Reproduce**
A webpage to do a POST call to this microservice.

**Expected behavior**
Returns 200 ok response and in this case, it creates a project in database

 - Browser Chrome

Note: I investigate and I solved it by adding the CorsPlug dependency

**Comment by dfucci** [comment]
Thank you for the fix @vvalvesga  
Can you open a pull request to integrate the changes and close this issue accordingly?

**Comment by vvalvesga** [comment]
Ok, I did it
Closed in #5
