### ISSUE TITLE
DB as volume

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/gds-edemocracy#4]
**Is your feature request related to a problem? Please describe.**
This microservice contains a PostgreSQL database but it is not added as a volume, therefore, when the container that is running is dropped, all the data will be erase

**Describe the solution you'd like**
Manage as volume

**Comment by vvalvesga** [comment]
See my fork repository https://github.com/vvalvesga/gds-edemocracy. I made changes for use Postgres as volume and to have persistance.

**Comment by dfucci** [comment]
@vvalvesga can you open a pull request. Thanks
