### ISSUE TITLE
Id user in login response

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/gds-edemocracy#8]
**Is your feature request related to a problem? Please describe.**
I need id user in many requests. 
When I login I pass the name and it returns me only the token.
When I register it returns "name" and "id" but it's not useful 

**Describe the solution you'd like**
In login response I would add id user.

**Comment by vvalvesga** [comment]
[Pull request here](https://github.com/OpenReqEU/gds-edemocracy/pull/9)

**Comment by dfucci** [comment]
Thank you @vvalvesga
